runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /class1\.html
  static_files: www/class1.html
  upload: www/class1.html

- url: /class2\.html
  static_files: www/class2.html
  upload: www/class2.html

- url: /class3ppd\.html
  static_files: www/class3ppd.html
  upload: www/class3ppd.html

- url: /class3ape\.html
  static_files: www/class3ape.html
  upload: www/class3ape.html


- url: /class4\.html
  static_files: www/class4.html
  upload: www/class4.html

- url: /class3examplehomework\.pdf
  static_files: www/example_homework.pdf
  upload: www/example_homework.pdf
